
pipeline {
  agent {
    docker {
      image 'docker.apple.com/aos/ol-jdk11-custom-maven'
      label 'rosdaos'
    }
  }

  options {
    timeout(time: 15, unit: 'MINUTES')
    disableConcurrentBuilds()
  }
  environment {
    branch = "${env.GIT_BRANCH}"
    pom = readMavenPom file: 'pom.xml'
    version = pom['version'].toUpperCase();
  }

  stages {
    stage('deploy') {
       when {
         expression { BRANCH_NAME ==~ /(master|develop)/ && env.VERSION ==~ /.*SNAPSHOT/}
       }  
      steps {
         sh 'echo hello on master and develop'
      }
    }
       
    stage('package') {
      when {
        not {
          expression { BRANCH_NAME ==~ /(master|develop)/ && env.VERSION ==~ /.*SNAPSHOT/ }
        }       
      }   
      steps {
         sh 'echo it is executing rest of mandd'
      }
    }
  }  
}
